# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NambaOneUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_created=True, db_index=True)),
                ('n1_user_id', models.IntegerField(verbose_name='ID пользователя в Namba One')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'ordering': ['datetime_created'],
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
