# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nambaoneuser',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
